import 'package:revon/models.dart';

final bookList = [
  Book(
    'The Great Gatsby',
    'F. Scott',
    'https://i0.wp.com/americanwritersmuseum.org/wp-content/uploads/2018/02/CK-3.jpg?resize=267%2C400&ssl=1',
    [
      Review(3.9, 'Best Book Ever'),
      Review(3.9, 'Best Book Ever'),
      Review(3.9, 'Best Book Ever'),
      Review(3.9, 'Best Book Ever'),
      Review(3.9, 'Best Book Ever'),
      Review(3.9, 'Best Book Ever'),
      Review(3.9, 'Best Book Ever'),
      Review(3.9, 'Best Book Ever'),
      Review(3.9, 'Best Book Ever'),
    ],
  ),
  Book('The Alchemist', 'Paulo Coelho',
      'https://images-na.ssl-images-amazon.com/images/I/71aFt4+OTOL.jpg', [
    Review(4.5, 'This book is amazing! Highly recommended.'),
    Review(3.0, 'It was an okay book, not my favorite.'),
  ]),
  Book(
      'To Kill a Mockingbird',
      'Harper Lee',
      'https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Mimus_polyglottos1.jpg/1024px-Mimus_polyglottos1.jpg',
      [
        Review(5.0, 'A timeless classic. Must-read.'),
        Review(4.0, 'A great book that everyone should read.'),
        Review(2.5, 'I did not enjoy this book.'),
        Review(2.5, 'I did not enjoy this book.'),
        Review(2.5, 'I did not enjoy this book.'),
        Review(4.0, 'A great book that everyone should read.'),
        Review(2.5, 'I did not enjoy this book.'),
        Review(4.0, 'A great book that everyone should read.'),
        Review(2.5, 'I did not enjoy this book.'),
        Review(4.0, 'A great book that everyone should read.'),
        Review(2.5, 'I did not enjoy this book.'),
        Review(2.5, 'I did not enjoy this book.'),
        Review(4.0, 'A great book that everyone should read.'),
        Review(2.5, 'I did not enjoy this book.'),
      ]),
  Book('1984', 'George Orwell',
      'https://images-na.ssl-images-amazon.com/images/I/71aFt4+OTOL.jpg', [
    Review(4.0, 'A chilling and thought-provoking book.'),
    Review(5.0, 'One of the best books I have ever read.'),
    Review(5.0, 'One of the best books I have ever read.'),
    Review(5.0, 'One of the best books I have ever read.'),
    Review(5.0, 'One of the best books I have ever read.'),
    Review(5.0, 'One of the best books I have ever read.'),
    Review(5.0, 'One of the best books I have ever read.'),
    Review(5.0, 'One of the best books I have ever read.'),
    Review(5.0, 'One of the best books I have ever read.'),
    Review(5.0, 'One of the best books I have ever read.'),
    Review(5.0, 'One of the best books I have ever read.'),
    Review(5.0, 'One of the best books I have ever read.'),
    Review(5.0, 'One of the best books I have ever read.'),
  ]),
  Book('The Prophecy', 'George Orwell',
      'https://m.media-amazon.com/images/I/51XXwdv2twL.jpg', [
    Review(4.0, 'A chilling and thought-provoking book.'),
    Review(5.0, 'One of the best books I have ever read.'),
    Review(5.0, 'One of the best books I have ever read.'),
    Review(5.0, 'One of the best books I have ever read.'),
    Review(5.0, 'One of the best books I have ever read.'),
    Review(5.0, 'One of the best books I have ever read.'),
    Review(5.0, 'One of the best books I have ever read.'),
    Review(5.0,
        'One of the best books I have ever read.One of the best books I have ever read.One of the best books I have ever read.One of the best books I have ever read.One of the best books I have ever read.One of the best books I have ever read.'),
    Review(5.0, 'One of the best books I have ever read.'),
  ]),
  Book(
      'Pride and Prejudice',
      'Jane Austen',
      'https://img.freepik.com/free-vector/digital-technology-background-with-abstract-wave-border_53876-117508.jpg',
      [
        Review(4.0, 'A classic romance novel.'),
        Review(3.5, 'An enjoyable read, but not my favorite.'),
        Review(3.5, 'An enjoyable read, but not my favorite.'),
        Review(3.5, 'An enjoyable read, but not my favorite.'),
        Review(3.5, 'An enjoyable read, but not my favorite.'),
        Review(3.5, 'An enjoyable read, but not my favorite.'),
        Review(3.5, 'An enjoyable read, but not my favorite.'),
        Review(3.5, 'An enjoyable read, but not my favorite.'),
        Review(3.5, 'An enjoyable read, but not my favorite.'),
        Review(3.5, 'An enjoyable read, but not my favorite.'),
        Review(3.5, 'An enjoyable read, but not my favorite.'),
        Review(3.5, 'An enjoyable read, but not my favorite.'),
      ]),
];
