// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0JeiK4H4bWKIPD0j5hDD_EzidEplUAt4',
    appId: '1:533982941937:web:887baa60298d7cc56b8f50',
    messagingSenderId: '533982941937',
    projectId: 'revon-f403f',
    authDomain: 'revon-f403f.firebaseapp.com',
    storageBucket: 'revon-f403f.appspot.com',
    measurementId: 'G-G22Y8B1KT4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_0zaVv07Se93gWESBKqcw1hat3XabCLY',
    appId: '1:533982941937:android:4652088e5fd571726b8f50',
    messagingSenderId: '533982941937',
    projectId: 'revon-f403f',
    storageBucket: 'revon-f403f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB43yKFF7Vs88DNQUefTZFRDoVzrbTFYVI',
    appId: '1:533982941937:ios:0e9d39060cc53aa26b8f50',
    messagingSenderId: '533982941937',
    projectId: 'revon-f403f',
    storageBucket: 'revon-f403f.appspot.com',
    iosClientId:
        '533982941937-27eu8obdj069ad9s93uhccic272bs3af.apps.googleusercontent.com',
    iosBundleId: 'com.example.revon',
  );
}
